### ISSUE TITLE
Error when starting the project in macOS development environment

### ISSUE THREAD

**Issue by jiehwa** [upscayl/upscayl#882]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

When I downloaded the project code, installed npm packages, and tried to start 'yarn dev', an error occurred.

<img width="517" alt="image" src="https://github.com/upscayl/upscayl/assets/3799526/a50450d3-137f-4acd-9bb3-04ae55705bdb">

### To Reproduce

upscayl package.json version：  "version": "2.11.5",

node version: v20.10.0

### Upscayl Version (or commit hash)

2.11.5

### Platform

Mac App Store

### OS Version

14.1.2

### GPU Name

Apple M1 Pro

### Logs

```sh
yarn dev
yarn run v1.22.19
$ tsc && electron .
App threw an error during load
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/zhongjianhua/Documents/GitHub/upscayl/node_modules/electron-next/node_modules/electron-is-dev/index.js from /Users/zhongjianhua/Documents/GitHub/upscayl/node_modules/electron-next/index.js not supported.
Instead change the require of /Users/zhongjianhua/Documents/GitHub/upscayl/node_modules/electron-next/node_modules/electron-is-dev/index.js in /Users/zhongjianhua/Documents/GitHub/upscayl/node_modules/electron-next/index.js to a dynamic import() which is available in all CommonJS modules.
    at Function._load (node:electron/js2c/node_init:2:13357)
    at Object.<anonymous> (/Users/zhongjianhua/Documents/GitHub/upscayl/node_modules/electron-next/index.js:7:15)
    at Function._load (node:electron/js2c/node_init:2:13357)
    at Object.<anonymous> (/Users/zhongjianhua/Documents/GitHub/upscayl/export/electron/index.js:15:41)
    at Function._load (node:electron/js2c/node_init:2:13357)
    at loadApplicationPackage (/Users/zhongjianhua/Documents/GitHub/upscayl/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:121:16)
    at Object.<anonymous> (/Users/zhongjianhua/Documents/GitHub/upscayl/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:233:9)
    at Function._load (node:electron/js2c/node_init:2:13357)
    at node:electron/js2c/browser_init:2:121197
    at node:electron/js2c/browser_init:2:121400
    at node:electron/js2c/browser_init:2:121404
    at Function._load (node:electron/js2c/node_init:2:13357)
2024-06-20 14:46:21.574 Electron[12672:7353085] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```

**Comment by aaronliu0130** [comment]
Try using pnpm instead.

**Comment by NayamAmarshe** [comment]
Don't use yarn.

**Comment by jiehwa** [comment]
> Try using pnpm instead. That's a problem with a dependency.

Thx! This is working
