### ISSUE TITLE
 build instructions do not produce a build, module 'dmg-license' not found

### ISSUE THREAD

**Issue by barf** [upscayl/upscayl#990]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

The build instructions do not reproduce a build on Ubuntu 22.04

### To Reproduce

After installing node using Volta:
```
$ git clone https://github.com/upscayl/upscayl
$ cd upscayl
$ npm install
$ npm run dist
$ npm run publish-app
```

### Upscayl Version (or commit hash)

bf62c684c24dde18b53270dd04bea87fd27fb087

### Platform

Linux

### OS Version

Ubuntu 22.04

### GPU Name

AMD

### Logs

```sh
$ npm run publish-app

> upscayl@2.11.5 publish-app
> tsc && npm run build && electron-builder -wlm --publish always


> upscayl@2.11.5 build
> tsc && next build renderer

  ▲ Next.js 14.2.10
  - Experiments (use with caution):
    · externalDir

 ✓ Linting and checking validity of types    
   Creating an optimized production build ...
   Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
   Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
   Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
 ✓ Compiled successfully
 ✓ Collecting page data    
 ✓ Generating static pages (3/3)
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (pages)                              Size     First Load JS
┌ ○ / (445 ms)                             239 kB          337 kB
├   /_app                                  0 B            98.1 kB
└ ○ /404                                   1.22 kB        99.3 kB
+ First Load JS shared by all              123 kB
  ├ chunks/framework-14efab3c3d1ed63b.js   44.8 kB
  ├ chunks/main-1af57f7b849fbe67.js        31.2 kB
  ├ chunks/pages/_app-fbab1090ca5c6263.js  20.3 kB
  ├ css/754d89d334fb0629.css               24.5 kB
  └ other shared chunks (total)            1.78 kB

○  (Static)  prerendered as static content

  • electron-builder  version=24.13.3 os=6.8.0-45-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  ⨯ Cannot find module 'dmg-license'
Require stack:
- /home/barf/src/upscayl/node_modules/dmg-builder/out/dmgLicense.js
- /home/barf/src/upscayl/node_modules/dmg-builder/out/dmg.js
- /home/barf/src/upscayl/node_modules/dmg-builder/out/dmgUtil.js
- /home/barf/src/upscayl/node_modules/app-builder-lib/out/macPackager.js
- /home/barf/src/upscayl/node_modules/app-builder-lib/out/packager.js
- /home/barf/src/upscayl/node_modules/app-builder-lib/out/index.js
- /home/barf/src/upscayl/node_modules/electron-builder/out/builder.js
- /home/barf/src/upscayl/node_modules/electron-builder/out/cli/cli.js
- /home/barf/src/upscayl/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot find module 'dmg-license'
Require stack:
- /home/barf/src/upscayl/node_modules/dmg-builder/out/dmgLicense.js
- /home/barf/src/upscayl/node_modules/dmg-builder/out/dmg.js
- /home/barf/src/upscayl/node_modules/dmg-builder/out/dmgUtil.js
- /home/barf/src/upscayl/node_modules/app-builder-lib/out/macPackager.js
- /home/barf/src/upscayl/node_modules/app-builder-lib/out/packager.js
- /home/barf/src/upscayl/node_modules/app-builder-lib/out/index.js
- /home/barf/src/upscayl/node_modules/electron-builder/out/builder.js
- /home/barf/src/upscayl/node_modules/electron-builder/out/cli/cli.js
- /home/barf/src/upscayl/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/barf/src/upscayl/node_modules/dmg-builder/src/dmgLicense.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/barf/src/upscayl/node_modules/dmg-builder/src/dmg.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
```

**Comment by barf** [comment]
This electron-builder issue may help shed some light:
https://github.com/electron-userland/electron-builder/issues/6520

**Comment by NayamAmarshe** [comment]
You're not supposed to publish the app, that's for the owners.

Use `npm run dist:mac`

**Comment by barf** [comment]
That would explain a lot, sorry about my confusion. I'm on Linux and `npm run dist:linux` did the trick!

Unrelated question: is there documentation on or tools for training new upscayl models somewhere? I couldn't find much about that.

**Comment by aaronliu0130** [comment]
https://github.com/xinntao/Real-ESRGAN/blob/master/docs/Training.md, then convert it with our wiki's model conversion guide.
